/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DronesDslStandaloneSetup extends DronesDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DronesDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
