/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DronesDslRuntimeModule extends AbstractDronesDslRuntimeModule {
}
