/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.behaviour.text.ui;

import hu.bme.mit.mdsd.dns2016.drones.behaviour.text.ui.AbstractBehavDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BehavDslUiModule extends AbstractBehavDslUiModule {
  public BehavDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
