/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text.validation;

import hu.bme.mit.mdsd.dns2016.drones.text.validation.AbstractDronesDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DronesDslValidator extends AbstractDronesDslValidator {
}
