/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.behaviour.text.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.mdsd.dns2016.drones.behaviour.text.parser.antlr.internal.InternalBehavDslParser;
import hu.bme.mit.mdsd.dns2016.drones.behaviour.text.services.BehavDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BehavDslParser extends AbstractAntlrParser {

	@Inject
	private BehavDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBehavDslParser createParser(XtextTokenStream stream) {
		return new InternalBehavDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BehavDSL";
	}

	public BehavDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BehavDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
