/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.mdsd.dns2016.drones.text.parser.antlr.internal.InternalDronesDslParser;
import hu.bme.mit.mdsd.dns2016.drones.text.services.DronesDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DronesDslParser extends AbstractAntlrParser {

	@Inject
	private DronesDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDronesDslParser createParser(XtextTokenStream stream) {
		return new InternalDronesDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Mission";
	}

	public DronesDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DronesDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
