/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel;

import hu.bme.mit.mdsd.dns2016.behaviour.DroneBehaviour;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behav DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavDSL#getImportedMission <em>Imported Mission</em>}</li>
 *   <li>{@link hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavDSL#getBehav <em>Behav</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavdslmodelPackage#getBehavDSL()
 * @model
 * @generated
 */
public interface BehavDSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Imported Mission</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imported Mission</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imported Mission</em>' containment reference.
   * @see #setImportedMission(Import)
   * @see hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavdslmodelPackage#getBehavDSL_ImportedMission()
   * @model containment="true"
   * @generated
   */
  Import getImportedMission();

  /**
   * Sets the value of the '{@link hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavDSL#getImportedMission <em>Imported Mission</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imported Mission</em>' containment reference.
   * @see #getImportedMission()
   * @generated
   */
  void setImportedMission(Import value);

  /**
   * Returns the value of the '<em><b>Behav</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behav</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behav</em>' containment reference.
   * @see #setBehav(DroneBehaviour)
   * @see hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavdslmodelPackage#getBehavDSL_Behav()
   * @model containment="true"
   * @generated
   */
  DroneBehaviour getBehav();

  /**
   * Sets the value of the '{@link hu.bme.mit.mdsd.dns2016.drones.behaviour.text.behavdslmodel.BehavDSL#getBehav <em>Behav</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Behav</em>' containment reference.
   * @see #getBehav()
   * @generated
   */
  void setBehav(DroneBehaviour value);

} // BehavDSL
