/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text.ui.contentassist;

import hu.bme.mit.mdsd.dns2016.drones.text.ui.contentassist.AbstractDronesDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DronesDslProposalProvider extends AbstractDronesDslProposalProvider {
}
