/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.behaviour.text;

import hu.bme.mit.mdsd.dns2016.drones.behaviour.text.AbstractBehavDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BehavDslRuntimeModule extends AbstractBehavDslRuntimeModule {
}
