/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.mdsd.dns2016.drones.text.ui;

import hu.bme.mit.mdsd.dns2016.drones.text.ui.AbstractDronesDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DronesDslUiModule extends AbstractDronesDslUiModule {
  public DronesDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
